# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_auto_20161006_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('element_type', models.IntegerField(choices=[(1, 'Box'), (2, 'Image'), (3, 'Offer')], verbose_name='Type')),
                ('element_type_en', models.IntegerField(choices=[(1, 'Box'), (2, 'Image'), (3, 'Offer')], null=True, verbose_name='Type')),
                ('element_type_fr', models.IntegerField(choices=[(1, 'Box'), (2, 'Image'), (3, 'Offer')], null=True, verbose_name='Type')),
                ('element_type_es', models.IntegerField(choices=[(1, 'Box'), (2, 'Image'), (3, 'Offer')], null=True, verbose_name='Type')),
                ('background_url', models.CharField(blank=True, max_length=50, verbose_name='Background URL')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('title_es', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('icon_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('icon_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('icon_es', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Main Content')),
                ('content_en', mezzanine.core.fields.RichTextField(null=True, verbose_name='Main Content')),
                ('content_fr', mezzanine.core.fields.RichTextField(null=True, verbose_name='Main Content')),
                ('content_es', mezzanine.core.fields.RichTextField(null=True, verbose_name='Main Content')),
                ('can_disappear', models.BooleanField(default=False, help_text='If true the content will disappear if screen width is reduced.', verbose_name='Can Disappear')),
                ('can_disappear_en', models.BooleanField(default=False, help_text='If true the content will disappear if screen width is reduced.', verbose_name='Can Disappear')),
                ('can_disappear_fr', models.BooleanField(default=False, help_text='If true the content will disappear if screen width is reduced.', verbose_name='Can Disappear')),
                ('can_disappear_es', models.BooleanField(default=False, help_text='If true the content will disappear if screen width is reduced.', verbose_name='Can Disappear')),
            ],
            options={
                'verbose_name': 'Element',
                'ordering': ('_order',),
                'verbose_name_plural': 'Elements',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('row_type', models.IntegerField(choices=[(1, 'Parallax'), (2, 'Gallery')], verbose_name='Type')),
                ('row_type_en', models.IntegerField(choices=[(1, 'Parallax'), (2, 'Gallery')], null=True, verbose_name='Type')),
                ('row_type_fr', models.IntegerField(choices=[(1, 'Parallax'), (2, 'Gallery')], null=True, verbose_name='Type')),
                ('row_type_es', models.IntegerField(choices=[(1, 'Parallax'), (2, 'Gallery')], null=True, verbose_name='Type')),
                ('background_url', models.CharField(blank=True, max_length=50, verbose_name='Background URL')),
                ('background_url_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Background URL')),
                ('background_url_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Background URL')),
                ('background_url_es', models.CharField(blank=True, max_length=50, null=True, verbose_name='Background URL')),
            ],
            options={
                'verbose_name': 'Element',
                'ordering': ('_order',),
                'verbose_name_plural': 'Elements',
            },
        ),
        migrations.CreateModel(
            name='UnifyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
            ],
            options={
                'verbose_name': 'Unify Page',
                'ordering': ('_order',),
                'verbose_name_plural': 'Unify Pages',
            },
            bases=('pages.page',),
        ),
        migrations.AddField(
            model_name='row',
            name='unifypage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='unifypage.UnifyPage'),
        ),
        migrations.AddField(
            model_name='element',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='unifypage.Row'),
        ),
    ]
