# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ('_order',), 'verbose_name': 'Row', 'verbose_name_plural': 'Rows'},
        ),
        migrations.RemoveField(
            model_name='element',
            name='can_disappear_en',
        ),
        migrations.RemoveField(
            model_name='element',
            name='can_disappear_es',
        ),
        migrations.RemoveField(
            model_name='element',
            name='can_disappear_fr',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_type_en',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_type_es',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_type_fr',
        ),
        migrations.RemoveField(
            model_name='element',
            name='icon_en',
        ),
        migrations.RemoveField(
            model_name='element',
            name='icon_es',
        ),
        migrations.RemoveField(
            model_name='element',
            name='icon_fr',
        ),
        migrations.RemoveField(
            model_name='row',
            name='background_url_en',
        ),
        migrations.RemoveField(
            model_name='row',
            name='background_url_es',
        ),
        migrations.RemoveField(
            model_name='row',
            name='background_url_fr',
        ),
        migrations.RemoveField(
            model_name='row',
            name='row_type_en',
        ),
        migrations.RemoveField(
            model_name='row',
            name='row_type_es',
        ),
        migrations.RemoveField(
            model_name='row',
            name='row_type_fr',
        ),
        migrations.AlterField(
            model_name='row',
            name='background_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Background URL'),
        ),
    ]
