# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0002_auto_20161020_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(1, 'Box'), (2, 'Image'), (3, 'Offer'), (4, 'Circle counter')], verbose_name='Type'),
        ),
    ]
