# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0003_auto_20161020_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='background_url',
        ),
        migrations.AddField(
            model_name='row',
            name='background',
            field=models.CharField(blank=True, max_length=500, verbose_name='Background'),
        ),
    ]
