# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0004_auto_20161021_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='background_url',
        ),
    ]
