# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0006_auto_20161021_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='size',
            field=models.IntegerField(default=0, help_text='Area separated in 12, 0 for auto', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='row',
            name='intro',
            field=mezzanine.core.fields.RichTextField(blank=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='row',
            name='intro_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='row',
            name='intro_es',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='row',
            name='intro_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='row',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='row',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='row',
            name='title_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='row',
            name='title_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='element',
            name='content',
            field=mezzanine.core.fields.RichTextField(blank=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='element',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='element',
            name='content_es',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='element',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='row',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name (hidden)'),
        ),
    ]
