# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0007_auto_20161021_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='size_sm',
            field=models.IntegerField(default=0, verbose_name='Size (little screen)'),
        ),
        migrations.AddField(
            model_name='element',
            name='size_xs',
            field=models.IntegerField(default=0, verbose_name='Size (mobile)'),
        ),
    ]
