# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0009_auto_20161021_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='row_type',
            field=models.IntegerField(choices=[(1, 'Default container'), (2, 'Parallax Counter'), (3, 'Parallax Counter V1'), (4, 'Parallax Counter V2'), (5, 'Parallax Counter V3'), (6, 'Parallax Counter V4'), (7, 'Gallery'), (8, 'Service Block V1'), (9, 'Service Block V2'), (10, 'Service Block V3'), (11, 'Service Block V4'), (12, 'Service Block V5'), (13, 'Service Block V6'), (14, 'Service Block V7'), (15, 'Service Block V8')], verbose_name='Type'),
        ),
    ]
