# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0012_auto_20161024_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='row_type',
            field=models.IntegerField(choices=[(1, 'Default container'), (5, 'Parallax Counter V3'), (6, 'Parallax Counter V4'), (7, 'Gallery'), (11, 'Service Block V4'), (18, 'TeamV3'), (28, 'Testimonials V6'), (29, 'Owl Carousel')], verbose_name='Type'),
        ),
    ]
