# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0014_auto_20161024_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_formula',
            field=models.BooleanField(default=False, verbose_name='Is a formula'),
        ),
    ]
