# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0015_element_is_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(5, 'Row Dependant'), (4, 'Counter'), (1, 'Box'), (2, 'Image'), (3, 'Offer')], verbose_name='Type'),
        ),
    ]
