# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0016_auto_20161026_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='icon',
            new_name='icon_class',
        ),
        migrations.AddField(
            model_name='element',
            name='icon_url',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon URL'),
        ),
    ]
