# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0017_auto_20161026_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Icon URL'),
        ),
    ]
