# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0018_auto_20161026_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='icon_url',
            field=models.URLField(blank=True, verbose_name='Icon URL'),
        ),
    ]
