# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0020_auto_20161026_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(5, 'Row Dependant'), (4, 'Counter'), (6, 'Vertical Progress Bar'), (7, 'Testimonial'), (1, 'Box'), (2, 'Image'), (3, 'Offer')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='element',
            name='is_formula',
            field=models.BooleanField(default=False, verbose_name='Contains a formula'),
        ),
    ]
