# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0021_auto_20161028_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='is_parallax',
            field=models.BooleanField(default=False, help_text='Display the Background with a Parallaxeffect', verbose_name='Parallax Background'),
        ),
    ]
