# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0022_row_is_parallax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='is_parallax',
        ),
        migrations.AddField(
            model_name='row',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='Display the Background with a "fixed" effect', verbose_name='Fixed Background'),
        ),
    ]
