# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0023_auto_20161031_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='more_url',
            field=models.URLField(blank=True, verbose_name='Link to more'),
        ),
        migrations.AddField(
            model_name='row',
            name='more_url',
            field=models.URLField(blank=True, verbose_name='Link to more'),
        ),
    ]
