# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0024_auto_20161101_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='can_disappear',
        ),
    ]
