# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0025_remove_element_can_disappear'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='more_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='Link to more'),
        ),
        migrations.AddField(
            model_name='element',
            name='more_url_es',
            field=models.URLField(blank=True, null=True, verbose_name='Link to more'),
        ),
        migrations.AddField(
            model_name='element',
            name='more_url_fr',
            field=models.URLField(blank=True, null=True, verbose_name='Link to more'),
        ),
        migrations.AddField(
            model_name='row',
            name='more_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='Link to more'),
        ),
        migrations.AddField(
            model_name='row',
            name='more_url_es',
            field=models.URLField(blank=True, null=True, verbose_name='Link to more'),
        ),
        migrations.AddField(
            model_name='row',
            name='more_url_fr',
            field=models.URLField(blank=True, null=True, verbose_name='Link to more'),
        ),
    ]
