# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0027_auto_20161101_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='row_type',
            field=models.IntegerField(choices=[(1, 'Default container'), (33, 'Block grid V2'), (5, 'Parallax Counter V3'), (6, 'Parallax Counter V4'), (7, 'Gallery'), (11, 'Service Block V4'), (18, 'Team V3'), (28, 'Testimonials V6'), (29, 'Owl Carousel'), (32, 'Breadcrumb V3')], verbose_name='Type'),
        ),
    ]
