# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0028_auto_20161102_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(5, 'Row Dependant'), (4, 'Counter'), (6, 'Vertical Progress Bar'), (7, 'Testimonial'), (1, 'Box'), (8, 'Course Block')], verbose_name='Type'),
        ),
    ]
