# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0031_auto_20161104_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifypage',
            name='show_image',
            field=models.BooleanField(default=False, verbose_name='Show image'),
        ),
    ]
