# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0032_unifypage_show_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Button text')),
                ('response', mezzanine.core.fields.RichTextField(verbose_name='Response')),
                ('send_email', models.BooleanField(default=True, help_text='To send an email to the email address supplied in the form upon submission, check this box.', verbose_name='Send email to user')),
                ('email_from', models.EmailField(blank=True, help_text='The address the email will be sent from', max_length=254, verbose_name='From address')),
                ('email_copies', models.CharField(blank=True, help_text='Provide a comma separated list of email addresses to be notified upon form submission. Leave blank to disable notifications.', max_length=200, verbose_name='Send email to others')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('email_message', models.TextField(blank=True, help_text='Emails sent based on the above options will contain each of the form fields entered. You can also enter a message here that will be included in the email.', verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Forms',
                'verbose_name': 'Form',
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(5, 'Row Dependant'), (2, 'Image'), (4, 'Counter'), (6, 'Vertical Progress Bar'), (7, 'Testimonial'), (1, 'Box'), (8, 'Course Block')], verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='form',
            name='element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unifypage.Element'),
        ),
    ]
