# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0038_auto_20161122_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='form',
        ),
        migrations.AddField(
            model_name='element',
            name='is_form',
            field=models.BooleanField(default=False, verbose_name='Is Form'),
        ),
        migrations.AlterField(
            model_name='element',
            name='size',
            field=models.IntegerField(default=0, help_text='Row are separated in 12 columns, this is the numberof columns (0 for automatic/equal for each elements)', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='element',
            name='size_sm',
            field=models.IntegerField(default=0, verbose_name='Size (~tablet)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='size_xs',
            field=models.IntegerField(default=0, verbose_name='Size (~mobile)'),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
