# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0039_auto_20161122_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('input_type', models.IntegerField(choices=[(1, 'Text Input'), (2, 'Text Area'), (2, 'Text Area'), (4, 'Checkbox')], verbose_name='Type')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Default Value')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Label')),
                ('label_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label')),
                ('label_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label')),
                ('label_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Placeholder')),
                ('placeholder_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Placeholder')),
                ('placeholder_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Placeholder')),
                ('placeholder_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='Placeholder')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('icon_class', models.CharField(blank=True, max_length=200, verbose_name='Icon Class')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.AddField(
            model_name='element',
            name='action',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link to send'),
        ),
        migrations.AddField(
            model_name='input',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='unifypage.Element'),
        ),
    ]
