# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0042_auto_20161123_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='button_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Button Label'),
        ),
    ]
