# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0047_remove_row_unifypages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='unifypage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='unifypage.UnifyPage'),
        ),
    ]
