# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models

def make_many_rows(apps, schema_editor):
    """
    Adds the Unifypage object in Row.unifypage to the
    many-to-many relationship in Row.unifypages
    """
    Row = apps.get_model('unifypage', 'Row')

    for row in Row.objects.all():
        row.unifypages.add(row.unifypage)



class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0048_auto_20161125_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='unifypages',
            field=models.ManyToManyField(related_name='rowss', to='unifypage.UnifyPage'),
        ),
        migrations.RunPython(make_many_rows),
    ]
