# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields

def make_page_rows(apps, schema_editor):
    """
    Adds the RowToPage object for each foreign key between a Row and a page
    """
    RowToPage = apps.get_model('unifypage', 'RowToPage')
    UnifyPage = apps.get_model('unifypage', 'UnifyPage')

    for page in UnifyPage.objects.all():
        for row in page.rows.all():
            rowToPage = RowToPage(page, row)



class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0049_row_unifypages'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowToPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToUnifypage', to='unifypage.Row')),
                ('unifypage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToRow', to='unifypage.UnifyPage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.RunPython(make_page_rows),
    ]
