# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0050_rowtopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='unifypages',
        ),
    ]
