# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 16:22
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0052_auto_20161128_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifypage',
            name='intro',
            field=mezzanine.core.fields.RichTextField(blank=True, verbose_name='Introduction text'),
        ),
    ]
