# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0053_unifypage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifypage',
            name='background',
            field=models.CharField(blank=True, max_length=500, verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='unifypage',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='Display the Background with a "fixed" effect', verbose_name='Fixed Background'),
        ),
    ]
