# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0055_auto_20161129_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='more_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link to more(elem)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='more_url_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to more(elem)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='more_url_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to more(elem)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='more_url_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to more(elem)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link to more(row)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to more(row)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to more(row)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to more(row)'),
        ),
    ]
