# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_image_url'),
        ('unifypage', '0057_unifypage_include_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultilangKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Word')),
                ('word_en', models.CharField(max_length=255, null=True, verbose_name='Word')),
                ('word_fr', models.CharField(max_length=255, null=True, verbose_name='Word')),
                ('word_es', models.CharField(max_length=255, null=True, verbose_name='Word')),
                ('blog_posts', models.ManyToManyField(blank=True, related_name='multilang_keywords', to='blog.BlogPost')),
            ],
        ),
        migrations.AlterField(
            model_name='element',
            name='icon_class',
            field=models.CharField(blank=True, help_text='One of the available icons for <a href="https://htmlstream.com/preview/unify-v1.9.7/shortcode_icon_general.html">unify</a>, for Font awesome add fa before (ex:fa  fa-gg)', max_length=50, verbose_name='Icon class'),
        ),
        migrations.AlterField(
            model_name='row',
            name='background',
            field=models.CharField(blank=True, help_text='CSS background propertyCan take: url(your_image_url), A color name (exemple grey), rgba(red, green, blue, opacity) with red, green and blue between 0 and 255 and opacity between 0 and 1, #hexvalue...', max_length=500, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='row',
            name='name',
            field=models.CharField(blank=True, help_text='A name to help differenciate the rows when setting order', max_length=50, verbose_name='Name (hidden)'),
        ),
        migrations.AddField(
            model_name='unifypage',
            name='multilang_keywords',
            field=models.ManyToManyField(blank=True, related_name='multilang_keywords', to='unifypage.MultilangKeyword'),
        ),
    ]
