# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0059_auto_20170112_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilangkeyword',
            name='salesref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref'),
        ),
        migrations.AlterField(
            model_name='multilangkeyword',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='multilangkeyword',
            name='word_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='multilangkeyword',
            name='word_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='multilangkeyword',
            name='word_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Word'),
        ),
    ]
