# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0061_auto_20170117_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowtopage',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUnifypages', to='unifypage.Row'),
        ),
        migrations.AlterField(
            model_name='rowtopage',
            name='unifypage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toRows', to='unifypage.UnifyPage'),
        ),
    ]
