# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0064_unifypage_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifypage',
            name='preview_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Preview Text'),
        ),
    ]
