# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0065_auto_20170120_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilangkeyword',
            name='blog_posts',
        ),
    ]
