# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0067_multilangkeyword_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilangkeyword',
            name='icon_url',
            field=models.CharField(default='', max_length=200, verbose_name='Icon URL'),
        ),
    ]
