# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0068_auto_20170203_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifypage',
            name='multilang_keywords',
            field=models.ManyToManyField(blank=True, related_name='pages', to='unifypage.MultilangKeyword'),
        ),
    ]
