# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0069_auto_20170208_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='background',
            field=models.CharField(blank=True, help_text='CSS background property<br/>Can take: url(your_image_url), <br/>A color name (exemple grey), <br/>rgba(red, green, blue, opacity) with red, green and blue between 0 and 255 and opacity between 0 and 1,<br/>#hexvalue...<br/>Or default_image to put the same as the page', max_length=500, verbose_name='Background'),
        ),
    ]
