# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0070_auto_20170209_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilangkeyword',
            name='color',
            field=models.CharField(choices=[('sea', 'Turquoise'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('dark', 'Dark'), ('brown', 'Brown'), ('green', 'Green'), ('aqua', 'Aqua'), ('light-green', 'Aquamarine'), ('light', 'Light'), ('orange', 'Orange'), ('dark-blue', 'Dark Blue')], default='orange', max_length=32, verbose_name='Word'),
        ),
    ]
