# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0071_multilangkeyword_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='css_class',
            field=models.CharField(blank=True, help_text='To potentially  add a CSS class to the englobing div', max_length=200, verbose_name='CSS Class'),
        ),
        migrations.AlterField(
            model_name='multilangkeyword',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue')], default='orange', max_length=32, verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='multilangkeyword',
            name='icon_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Icon URL'),
        ),
    ]
