# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0072_auto_20170214_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='css_class',
            field=models.CharField(blank=True, help_text='To potentially  add a CSS class to the englobing div', max_length=200, verbose_name='CSS Class'),
        ),
        migrations.AlterField(
            model_name='multilangkeyword',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green')], default='orange', max_length=32, verbose_name='Word'),
        ),
    ]
