# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0073_auto_20170214_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilangkeyword',
            name='color',
        ),
    ]
