# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0076_auto_20170214_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifypage',
            name='show_image',
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(5, 'Row Dependant'), (2, 'Image'), (4, 'Counter'), (6, 'Vertical Progress Bar'), (7, 'Testimonials'), (1, 'Box'), (8, 'Course Block'), (9, 'Form'), (10, 'Image zoom'), (11, 'Blog Post Block')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='element',
            name='size',
            field=models.IntegerField(default=0, help_text='Row are separated in 12 columns, this is the numberof columns (0 for automatic/equal for each elements)<a href="http://getbootstrap.com/css/#grid-example-basic"> help</a>', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url',
            field=models.CharField(blank=True, help_text='A button a the bottom of the row will link to this URL. For a Youtube video Row, put here the ID of the video', max_length=200, verbose_name='Link to more(row)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url_en',
            field=models.CharField(blank=True, help_text='A button a the bottom of the row will link to this URL. For a Youtube video Row, put here the ID of the video', max_length=200, null=True, verbose_name='Link to more(row)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url_es',
            field=models.CharField(blank=True, help_text='A button a the bottom of the row will link to this URL. For a Youtube video Row, put here the ID of the video', max_length=200, null=True, verbose_name='Link to more(row)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='more_url_fr',
            field=models.CharField(blank=True, help_text='A button a the bottom of the row will link to this URL. For a Youtube video Row, put here the ID of the video', max_length=200, null=True, verbose_name='Link to more(row)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='row_type',
            field=models.IntegerField(choices=[(1, 'Default container'), (11, 'Service Block V4'), (34, 'Block grid V2'), (5, 'Parallax Counter V3'), (6, 'Parallax Counter V4'), (7, 'Gallery'), (18, 'Team V3'), (28, 'Testimonials V6'), (29, 'Owl Carousel'), (38, 'Logo Owl Carousel'), (39, 'Masonry'), (32, 'Breadcrumb V3'), (36, 'Basic Map'), (40, 'Youtube Video')], verbose_name='Type'),
        ),
    ]
