# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attendee_number', models.IntegerField(blank=True, verbose_name='Attendee Number')),
            ],
        ),
    ]
