# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0002_auto_20161025_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
    ]
