# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0003_event_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('opportunity_ratio', models.IntegerField(blank=True, verbose_name='Opportunity Ratio')),
            ],
        ),
    ]
