# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0005_auto_20161026_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('contact_title', models.CharField(max_length=100, verbose_name='Contact Title')),
                ('text', models.CharField(max_length=32768, verbose_name='Text')),
                ('authorised', models.BooleanField(default=False, verbose_name='Authorised')),
                ('ranking', models.PositiveSmallIntegerField(default=5, verbose_name='Ranking')),
            ],
        ),
    ]
