# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='lang_code',
            field=models.CharField(default='en', max_length=20, verbose_name='Language code'),
        ),
    ]
