# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0007_testimonial_lang_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='authorised',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='lang_code',
            field=models.CharField(default='en', max_length=2, verbose_name='Language code'),
        ),
    ]
