# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0008_auto_20161027_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='contact_title',
            field=models.CharField(max_length=1300, verbose_name='Contact Title'),
        ),
    ]
