# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0009_auto_20161027_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='creation_date',
            field=models.DateField(null=True, verbose_name='Creation Date'),
        ),
    ]
