# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magentrix', '0010_testimonial_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('description', models.CharField(max_length=32768, verbose_name='Description')),
                ('lang_code', models.CharField(default='en', max_length=2, verbose_name='Language code')),
                ('creation_date', models.DateField(null=True, verbose_name='Creation Date')),
            ],
        ),
    ]
