from django.utils.translation import ugettext_lazy as _

CONTAINER = 1
PARALLAXC = 2
PARALLAXC1 = 3
PARALLAXC2 = 4
PARALLAXC3 = 5
PARALLAXC4 = 6
GALLERY = 7
SERVICEBLOCK1 = 8
SERVICEBLOCK2 = 9
SERVICEBLOCK3 = 10
SERVICEBLOCK4 = 11
SERVICEBLOCK5 = 12
SERVICEBLOCK6 = 13
SERVICEBLOCK7 = 14
SERVICEBLOCK8 = 15
TEAM1 = 16
TEAM2 = 17
TEAM3 = 18
TEAM4 = 19
TEAM5 = 20
TEAM6 = 21
TEAM7 = 22
TESTIMONIALS1 = 23
TESTIMONIALS2 = 24
TESTIMONIALS3 = 25
TESTIMONIALS4 = 26
TESTIMONIALS5 = 27
TESTIMONIALS6 = 28
OWLCAROUSEL = 29
BREADCRUMB1 = 30
BREADCRUMB2 = 31
BREADCRUMB3 = 32
BLOCKGRID1 = 33
BLOCKGRID2 = 34
BLOCKGRID3 = 35
BASICMAP = 36
PANORAMAP = 37
LOGOCAROUSEL = 38
MASONRY = 39
YOUTUBEVIDEO = 40

NAMES = (
    (CONTAINER, _("Default container")),
    (SERVICEBLOCK4, _("Service Block V4")),
    (BLOCKGRID2, _("Block grid V2")),
    (PARALLAXC3, _("Parallax Counter V3")),
    (PARALLAXC4, _("Parallax Counter V4")),
    (GALLERY, _("Gallery")),
    (TEAM3, _("Team V3")),
    (TESTIMONIALS6, _("Testimonials V6")),
    (OWLCAROUSEL, _("Owl Carousel")),
    (LOGOCAROUSEL, _("Logo Owl Carousel")),
    (MASONRY, _("Masonry")),
    (BREADCRUMB3, _("Breadcrumb V3")),
    (BASICMAP, _("Basic Map")),
    (YOUTUBEVIDEO, _("Youtube Video")),
)
