# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='is_published',
        ),
    ]
