# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0002_auto_20161213_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='target_delegates',
            field=models.IntegerField(default=0, verbose_name='Target Delegates'),
        ),
    ]
