# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0003_coursepage_target_delegates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LnxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=18, null=True, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Sync')),
                ('image_type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='course_url',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='event_url',
        ),
    ]
