# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0004_auto_20161214_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnximage',
            name='mark_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ln2xevents.MarketingContent'),
        ),
    ]
