# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0006_courseimagebreaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimagebreaker',
            options={'ordering': ('_order',)},
        ),
        migrations.AlterModelOptions(
            name='coursepage',
            options={'ordering': ['title'], 'verbose_name': 'Course Page', 'verbose_name_plural': 'Course Pages'},
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'ordering': ['-start_date', 'country'], 'verbose_name': 'Event Page', 'verbose_name_plural': 'Event Pages'},
        ),
        migrations.AddField(
            model_name='courseimagebreaker',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='courseimagebreaker',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_breakers', to='ln2xevents.CoursePage'),
        ),
    ]
