# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0007_auto_20161220_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Page Content', 'verbose_name_plural': 'Page Contents'},
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='creation_date',
            field=models.DateField(null=True, verbose_name='Creation Date'),
        ),
    ]
