# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0008_auto_20161221_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcontent',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ln2xevents.PageContent'),
        ),
        migrations.AlterField(
            model_name='marketingcontent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ln2xevents.CoursePage'),
        ),
        migrations.AlterField(
            model_name='marketingcontent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ln2xevents.EventPage'),
        ),
    ]
