# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0009_auto_20161222_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=18, null=True, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Sync')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Name')),
                ('ranking', models.IntegerField(default=5, verbose_name='Ranking')),
                ('lang_code', models.CharField(default='en', max_length=2, verbose_name='Language code')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('contact_title', models.CharField(blank=True, max_length=1300, null=True, verbose_name='Contact Title')),
                ('testimonial_text', models.TextField(blank=True, max_length=32768, verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
