# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0010_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
    ]
