# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0011_remove_testimonial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='venue_description',
            field=models.TextField(blank=True, max_length=32768, verbose_name='Venue Description'),
        ),
        migrations.AddField(
            model_name='oldurl',
            name='event_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='ln2xevents.EventPage'),
        ),
    ]
