# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0012_auto_20170111_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OldUrl',
            new_name='OldSlug',
        ),
    ]
