# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0059_auto_20170112_1644'),
        ('ln2xevents', '0014_pagecontent_is_keyword_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='multilang_keywords',
            field=models.ManyToManyField(blank=True, related_name='course_pages', to='unifypage.MultilangKeyword'),
        ),
    ]
