# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0015_coursepage_multilang_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='level',
            field=models.CharField(choices=[('advanced', 'Advanced'), ('mid-level', 'Mid-Level'), ('basic', 'Basic')], default='basic', max_length=15, verbose_name='Level'),
        ),
    ]
