# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0016_coursepage_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='macro_region',
            field=models.CharField(blank=True, max_length=1300, null=True, verbose_name='Macro Region'),
        ),
    ]
