# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0017_auto_20170117_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='product_reference',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
