# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0019_auto_20170119_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='ln2xevents.CoursePage'),
        ),
    ]
