# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0020_testimonial_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=18, null=True, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Sync')),
                ('contact_name', models.CharField(blank=True, max_length=121, null=True, verbose_name='Name')),
                ('contact_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title')),
                ('account_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Account Name')),
                ('bio', models.CharField(blank=True, max_length=32768, null=True, verbose_name='Bio')),
                ('custom_profile_image', models.URLField(blank=True, null=True, verbose_name='Custom Profile Image')),
                ('custom_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Custom Name')),
                ('anonymous_contact_name', models.BooleanField(default=True, verbose_name='Anonymous Contact Name')),
                ('anonymous_title_name', models.BooleanField(default=True, verbose_name='Anonymous Title Name')),
                ('anonymous_account_name', models.BooleanField(default=True, verbose_name='Anonymous Account Name')),
                ('speaker_country', models.CharField(blank=True, max_length=1300, null=True, verbose_name='Speaker Country')),
                ('speaker_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Speaker Rating')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ln2xevents.EventPage')),
            ],
            options={
                'verbose_name_plural': 'Speakers',
                'verbose_name': 'Speaker',
            },
        ),
    ]
