# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0021_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='ln2xevents.EventPage'),
        ),
    ]
