# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0022_auto_20170123_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='ln2xevents.CoursePage'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='level',
            field=models.CharField(choices=[('advanced', 'Expert'), ('mid-level', 'Professional'), ('basic', 'Introductory')], default='basic', max_length=15, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='address',
            field=models.TextField(blank=True, max_length=255, verbose_name='Address'),
        ),
    ]
