# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0026_auto_20170126_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=18, null=True, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Sync')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Name')),
                ('account_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Account Name')),
                ('account_logo', models.URLField(blank=True, null=True, verbose_name='Account Logo')),
                ('account_description', models.TextField(blank=True, null=True, verbose_name='Account Description')),
                ('sponsor_type', models.CharField(blank=True, choices=[('Strategic Partners', 'Strategic Partners'), ('Sponsors', 'Sponsors'), ('Media Partners', 'Media Partners'), ('In Partnership with', 'In Partnership with')], max_length=255, null=True, verbose_name='Sponsor Type')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Custom Description')),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Name')),
                ('custom_logo', models.URLField(blank=True, null=True, verbose_name='Custom Logo')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='ln2xevents.EventPage')),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
                'verbose_name': 'Sponsor',
            },
        ),
    ]
