# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifypage', '0065_auto_20170120_1542'),
        ('ln2xevents', '0027_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='multilang_keywords',
            field=models.ManyToManyField(blank=True, related_name='event_pages', to='unifypage.MultilangKeyword'),
        ),
    ]
