# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0029_testimonial_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldslug',
            name='course_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='ln2xevents.CoursePage'),
        ),
    ]
