# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0030_oldslug_course_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='category',
            field=models.CharField(blank=True, choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Training', 'Training'), ('e-Learning', 'e-Learning')], max_length=50, verbose_name='Category'),
        ),
    ]
