# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0031_auto_20170203_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='sold_out',
            field=models.BooleanField(default=False, verbose_name='Sold Out'),
        ),
    ]
