# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 14:36
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0032_eventpage_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='terms_conditions',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Terms and Conditions'),
        ),
    ]
