# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0033_auto_20170209_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location_thumb',
            field=models.URLField(blank=True, null=True, verbose_name='Location Thumb'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='speaker_intro',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Speaker Intro'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='sponsor_intro',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Sponsor Intro'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='sponsor_list_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sponsor List Title'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='times',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Event Times'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='venue_description',
            field=models.TextField(blank=True, max_length=32768, null=True, verbose_name='Venue Description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Venue Name'),
        ),
    ]
