# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0034_auto_20170209_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='category',
            field=models.CharField(blank=True, choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Training', 'Training'), ('e-Learning', 'e-Learning')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='thumb',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Thumb'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='lnximage',
            name='image_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='lnximage',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='lnximage',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='marketingcontent',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='rich_text',
            field=mezzanine.core.fields.RichTextField(blank=True, max_length=32768, null=True, verbose_name='Rich Text'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='last_sync',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.TextField(blank=True, max_length=32768, null=True, verbose_name='Text'),
        ),
    ]
