# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0035_auto_20170209_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='category',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='delivery_format',
            field=models.CharField(blank=True, choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Training', 'Training'), ('e-Learning', 'e-Learning')], max_length=50, null=True, verbose_name='Delivery Format'),
        ),
    ]
