# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln2xevents', '0037_auto_20170215_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration(min)'),
        ),
    ]
